export const SERVICES = [
  "Kitchen Remodel",
  "Bathroom Remodel",
  "Basement Finish",
  "Flooring & Tile",
  "Paint & Finish",
  "Deck & Patio",
  "Siding & Roof",
  "Insulation & Drywall",
  "Water Damage Restoration",
  "Plumbing",
  "Electrical",
  "HVAC",
  "Window & Door",
  "Carpet Cleaning",
  "General Renovation",
];
